name: CannabisLawSociety
environment:
  sdk: any
dependencies:
  csv: any
  flutter_web: any
  flutter_web_ui: any
  http: any
dev_dependencies:
  build_runner: any
  build_web_compilers: any
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
